include:
  - ./docker/compose.db.yaml
services:
  backend_app:
    container_name: zatsunen_backend_app
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.22.4-alpine

        RUN apk update && apk add --no-cache ca-certificates tar curl && update-ca-certificates
        RUN go install github.com/air-verse/air@v1.52.2

        WORKDIR /app

        # COPY go.mod go.sum ./
        COPY go.mod ./
        RUN go mod download
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      # gcs:
      #   condition: service_started
    command: air -c .air.toml
  nginx:
    container_name: zatsunen_nginx
    image: nginx
    ports:
      - "3000:3000"
      - "3002:3002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend_app
      - db
