name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    name: go test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TZ: "Asia/Tokyo"
      STORAGE_URL: "localhost:4443"
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: start database
        run: docker compose -f ./docker/compose.db.yaml --profile healthcheck up -d
      - name: go module download
        run: go mod download
      - name: install tparse
        run: go install github.com/mfridman/tparse@latest
      - name: build
        run: go build -v ./...
      - name: test
        run: go test ./... -cover -json | tee ./go-test.out | tparse
      - name: add job summary
        if: always()
        run: |
          tparse -all -file ./go-test.out -format markdown >> $GITHUB_STEP_SUMMARY
